newtable:
  columns:
  - column_index: 0
    column_type: STRING
    key_column: null
    mapped_column_path: null
    original_column: a
  - column_index: 1
    column_type: STRING
    key_column: null
    mapped_column_path: null
    original_column: b
  create_time: '2025-06-05T08:18:01.558478Z'
  description: null
  resource_name: projects/sharp-bulwark-412718/locations/us/instances/6b9f77b6-1fe3-40ad-8746-7a26dc366ac2/dataTables/newtable
  row_time_to_live: null
  rule_associations_count: null
  rules: null
  update_time: '2025-06-05T08:18:01.558478Z'
  uuid: 4292eb98ded44a5ca34b405205d03262
